export { BrowserIcon } from './BrowserIcon'
export { ChromeIcon } from './ChromeIcon'
export { DesktopIcon } from './DesktopIcon'
export { FireFoxIcon } from './FireFoxIcon'
export { MobileIcon } from './MobileIcon'
export { OperaIcon } from './OperaIcon'
